import "./style.css";
import Player from "./Player.js";
import DOM from "./DOM";
import Ship from "./Ship.js";
import GameController from "./GameController.js";
const playerOne = new Player();
const shipOne = new Ship(1);
const shipTwo = new Ship(4);
playerOne.gameboard.place(shipOne, [1, 1]);
playerOne.gameboard.place(shipTwo, [5, 2]);
playerOne.gameboard.place(shipTwo, [5, 3]);
playerOne.gameboard.place(shipTwo, [5, 4]);
playerOne.gameboard.place(shipTwo, [5, 5]);
DOM.initializeBoard(playerOne, 1);
const playerTwo = new Player();
DOM.initializeBoard(playerTwo, 2);
